In [1]:
#Importer les librairies
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
import os

# Spécifiez le nouveau répertoire
new_directory = "/Users/esan/Desktop/OPCR/Projet7"

# Changer le répertoire courant
os.chdir(new_directory)

# Vérifiez le répertoire courant après le changement
print(os.getcwd())

/Users/esan/Desktop/OPCR/Projet7

In [3]:
df = pd.read_csv("training.1600000.processed.noemoticon.csv", encoding='latin-1')  # Spécifiez l'encodage si nécessaire
print(df.shape)

(1599999, 6)

In [4]:
df.sample(10)

,0,1467810369,Mon Apr 06 22:19:45 PDT 2009,NO_QUERY,_TheSpecialOne_,"@switchfoot http://twitpic.com/2y1zl - Awww, that's a bummer. You shoulda got David Carr of Third Day to do it. ;D"
1160685,4,1979449695,Sun May 31 03:05:48 PDT 2009,NO_QUERY,yojibee,@magnebergan I would recommend waiting for th...
1570433,4,2188595871,Mon Jun 15 22:11:22 PDT 2009,NO_QUERY,jonerickson,"@emiliocavazos nice, that RSX was my high scho..."
767514,0,2300496659,Tue Jun 23 14:13:17 PDT 2009,NO_QUERY,theCHEEKsterr,@Juzlik3muzik LMAOO but yu not tryna be in a g...
433584,0,2064994223,Sun Jun 07 07:39:21 PDT 2009,NO_QUERY,droyd,@davemidell_IFD dude i love forensic files! A...
841384,4,1563447722,Sun Apr 19 22:52:38 PDT 2009,NO_QUERY,donnamatrix,@LKid If you haven't found anyone... I work do...
1581017,4,2190137938,Tue Jun 16 01:52:36 PDT 2009,NO_QUERY,katekatekaate,@chunkofplastic ninas 18th! we totally can see...
153840,0,1933043389,Tue May 26 22:51:02 PDT 2009,NO_QUERY,iCONtips,...im over it. Ugh. I never WIN. At anything. ...
1494086,4,2069624062,Sun Jun 07 16:13:11 PDT 2009,NO_QUERY,siulu,Going to watch Up! 3d glasses in hand and rea...
434462,0,2065192922,Sun Jun 07 08:05:32 PDT 2009,NO_QUERY,MelissaM1228,"perhaps auditioning today, and definitely watc..."
1538577,4,2179901983,Mon Jun 15 09:44:25 PDT 2009,NO_QUERY,akorittko,Yay flowers are coming back from last year. Ca...

In [5]:
df.sample(5)

,0,1467810369,Mon Apr 06 22:19:45 PDT 2009,NO_QUERY,_TheSpecialOne_,"@switchfoot http://twitpic.com/2y1zl - Awww, that's a bummer. You shoulda got David Carr of Third Day to do it. ;D"
655970,0,2240268020,Fri Jun 19 09:32:30 PDT 2009,NO_QUERY,Meliissa_,Now it's holidays i miss smoking and i miss m...
1179035,4,1981675970,Sun May 31 09:39:33 PDT 2009,NO_QUERY,MusikFareak,Listening to music while cleaning my room and ...
316344,0,2002386472,Tue Jun 02 04:03:38 PDT 2009,NO_QUERY,adylma,French plane from Rio de Janeiro to Paris hit ...
673640,0,2247551939,Fri Jun 19 19:16:03 PDT 2009,NO_QUERY,starteacher2008,Trying to figure out how to twitter.......so f...
1195883,4,1984700065,Sun May 31 15:37:48 PDT 2009,NO_QUERY,martinsandoval,"Bye guys! From this minute, I am hardworking!..."

In [6]:
# Afficher les colonnes du DataFrame
print(df.columns)

Index(['0', '1467810369', 'Mon Apr 06 22:19:45 PDT 2009', 'NO_QUERY',
       '_TheSpecialOne_',
       '@switchfoot http://twitpic.com/2y1zl - Awww, that's a bummer.  You shoulda got David Carr of Third Day to do it. ;D'],
      dtype='object')

In [7]:
data = df[["0", "@switchfoot http://twitpic.com/2y1zl - Awww, that's a bummer.  You shoulda got David Carr of Third Day to do it. ;D"]]

In [8]:
# Renommer les colonnes en utilisant un dictionnaire
data = data.rename(columns={
    '0': 'Etiquette',
    '@switchfoot http://twitpic.com/2y1zl - Awww, that\'s a bummer.  You shoulda got David Carr of Third Day to do it. ;D': 'tweet'
})

# Afficher les noms des colonnes pour vérifier
print(data.columns)

Index(['Etiquette', 'tweet'], dtype='object')

In [9]:
data.sample(10)

         Etiquette                                              tweet
645033           0  watching the pouring rain from my window, anot...
627156           0  Does anyone out there from Hogwarts know the s...
177391           0  back from dr. appt. no real diagnosis (hmph), ...
1297520          4  @ChuckOff why limit your story to 140 ch. Tell...
134856           0  I was feeling GREAT until I pulled up to work ...
521776           0  @onesoulfulnegro oh my goodness honey  you sho...
2074             0  Woken up by someone hammering &gt;&lt; they ha...
482248           0  Decided its time to upgrade to the new SK lx.....
308423           0  Excited about Iron Maiden RB DLC like everyone...
1160601          4  A bagel with strawberry cream cheese, and coff...

In [10]:
data.shape

(1599999, 2)

In [11]:
data["Etiquette"].value_counts()

Etiquette
4    800000
0    799999
Name: count, dtype: int64

In [12]:
# Supprimer les doublons basés sur la colonne 'tweet'
data_unique = data.drop_duplicates(subset='tweet')

# Afficher le nombre de lignes avant et après suppression des doublons
print(f"Nombre de lignes avant suppression des doublons : {len(data)}")
print(f"Nombre de lignes après suppression des doublons : {len(data_unique)}")

# Afficher les premières lignes du DataFrame après suppression des doublons
print(data_unique.head())

Nombre de lignes avant suppression des doublons : 1599999
Nombre de lignes après suppression des doublons : 1581465
   Etiquette                                              tweet
0          0  is upset that he can't update his Facebook by ...
1          0  @Kenichan I dived many times for the ball. Man...
2          0    my whole body feels itchy and like its on fire
3          0  @nationwideclass no, it's not behaving at all....
4          0                      @Kwesidei not the whole crew

In [13]:
data_unique["Etiquette"].value_counts()

Etiquette
4    791281
0    790184
Name: count, dtype: int64

In [14]:
# Calculer le nombre total d'occurrences
total_counts = data_unique['Etiquette'].value_counts()
total = total_counts.sum()

In [15]:
# Calculer le pourcentage de chaque étiquette
percentage_counts = (total_counts / total) * 100

# Afficher les résultats
print(percentage_counts)

Etiquette
4    50.034683
0    49.965317
Name: count, dtype: float64

In [16]:
# Afficher les pourcentages avec 2 décimales
for etiquette, percentage in percentage_counts.items():
    print(f"Étiquette : {etiquette}, Pourcentage : {percentage:.2f}%")

Étiquette : 4, Pourcentage : 50.03%
Étiquette : 0, Pourcentage : 49.97%

### <a name="C3">3 - Prétraitement du texte avec NLP</a>

In [18]:
# Importations pour le traitement du langage naturel
import nltk
import string
from nltk.stem import WordNetLemmatizer

# Téléchargement des ressources nécessaires pour nltk
nltk.download('stopwords')
nltk.download('punkt')
nltk.download('words')
nltk.download('wordnet')

[nltk_data] Downloading package stopwords to /Users/esan/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package punkt to /Users/esan/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package words to /Users/esan/nltk_data...
[nltk_data]   Package words is already up-to-date!
[nltk_data] Downloading package wordnet to /Users/esan/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!

True

In [19]:
# Liste des mots vides (stop words) en anglais
stopwords = nltk.corpus.stopwords.words('english')
# Ensemble de mots en anglais
words = set(nltk.corpus.words.words())
# Initialisation de l'objet lemmatizer pour la lemmatisation des mots
lemmatizer = WordNetLemmatizer()

In [20]:
def Preprocess_listofSentence(listofSentence):
    # Initialisation de la liste pour stocker les phrases prétraitées
    preprocess_list = []

    # Parcours de chaque phrase dans la liste d'entrée
    for sentence in listofSentence:
        # Retire la ponctuation et convertit en minuscules
        sentence_w_punct = "".join([i.lower() for i in sentence if i not in string.punctuation])

        # Supprime les chiffres de la phrase
        sentence_w_num = ''.join(i for i in sentence_w_punct if not i.isdigit())

        # Tokenization de la phrase
        tokenize_sentence = nltk.tokenize.word_tokenize(sentence_w_num)

        # Supprime les stopwords de la phrase
        words_w_stopwords = [i for i in tokenize_sentence if i not in stopwords]

        # Lemmatization des mots
        words_lemmatize = (lemmatizer.lemmatize(w) for w in words_w_stopwords)

        # Crée une phrase propre en assemblant les mots lemmatisés
        sentence_clean = ' '.join(w for w in words_lemmatize if w.lower() in words or not w.isalpha())

        # Ajoute la phrase propre à la liste des résultats
        preprocess_list.append(sentence_clean)

    # Retourne la liste des phrases prétraitées
    return preprocess_list

In [21]:
# Appliquer la fonction de prétraitement aux données textuelles de la colonne 'tweet' du DataFrame 
preprocess_list = Preprocess_listofSentence(data_unique['tweet'])

In [22]:
print('Phrase nettoyée : '+preprocess_list[99])

Phrase nettoyée : body missing northern girl found police found remains missing northern girl

In [23]:
data_unique['Tweet_corrige'] = Preprocess_listofSentence(data_unique['tweet'])

/var/folders/qk/2sbz41_s2dl32bv7jdy_gqrh0000gn/T/ipykernel_44853/4056319516.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_unique['Tweet_corrige'] = Preprocess_listofSentence(data_unique['tweet'])

In [24]:
data_unique.sample(6)

,Etiquette,tweet,Tweet_corrige
1030232,4,Limited Edition Coin Purses Now Available: Top...,limited edition coin purse available top city ...
2552,0,this is exactly why as cities burn worries me ...,exactly city burn worry quota city burn third ...
1188499,4,@DanaLouLou if you are ever in my area i will ...,ever area take eat one
1045379,4,Up since 6am.. Ive got uni tonight nd my mates...,since got tonight mate party
1560532,4,@macspeech wow. I think I have several cousin...,wow think several cousin growling right
1151893,4,just made a twitter account.. so new at this lol,made twitter account new

In [50]:
data = data_unique[["Etiquette", "Tweet_corrige"]]
data.head()

   Etiquette                                      Tweet_corrige
0          0  upset cant update might cry result school toda...
1          0                  many time ball save rest go bound
2          0                    whole body feel itchy like fire
3          0                                       mad cant see
4          0                                         whole crew

In [52]:
data.shape

(1581465, 2)

In [54]:
# Compter le nombre de lignes manquantes dans la colonne 'Tweet_corrige'
missing_values_count = data['Tweet_corrige'].isna().sum()

# Afficher le nombre de lignes manquantes
print(f"Nombre de lignes manquantes dans 'Tweet_corrige' : {missing_values_count}")

Nombre de lignes manquantes dans 'Tweet_corrige' : 0

In [ ]:
!pip install wordcloud

In [ ]:
from wordcloud import WordCloud
import matplotlib.pyplot as plt  # Importation de matplotlib pour afficher le nuage de mots

# Concaténer tous les textes prétraités en une seule chaîne
all_texts = ' '.join(data['Tweet_corrige'].values)

# Créer l'objet WordCloud
wordcloud = WordCloud(width=800, height=400, random_state=42, max_font_size=100, background_color='white').generate(all_texts)

# Afficher le nuage de mots
plt.figure(figsize=(10, 6))
plt.imshow(wordcloud, interpolation='bilinear')
plt.axis('off')  # Supprimer les axes
plt.show()

In [ ]:
# Prendre un échantillon aléatoire de 10 % des données
data_echant = data.sample(frac=0.1, random_state=42)

In [ ]:
data_echant.shape

In [ ]:
data_echant.to_csv('/Users/esan/Desktop/OPCR/Projet7/data_echant.csv', index=False)